<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KabupatenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Data kabupaten untuk provinsi Nanggroe Aceh Darussalam (provinsi_id = 1)
        $kabupatens = [
            ['provinsi_id' => 1, 'nama_kabupaten' => 'Kab. Aceh Barat'],
            ['provinsi_id' => 1, 'nama_kabupaten' => 'Kab. Aceh Barat Daya'],
            ['provinsi_id' => 1, 'nama_kabupaten' => 'Kab. Aceh Besar'],
            ['provinsi_id' => 1, 'nama_kabupaten' => 'Kab. Aceh Jaya'],
            ['provinsi_id' => 1, 'nama_kabupaten' => 'Kab. Aceh Selatan'],
            ['provinsi_id' => 1, 'nama_kabupaten' => 'Kab. Aceh Singkil'],
            ['provinsi_id' => 1, 'nama_kabupaten' => 'Kab. Aceh Tamiang'],
            ['provinsi_id' => 1, 'nama_kabupaten' => 'Kab. Aceh Tengah'],
            ['provinsi_id' => 1, 'nama_kabupaten' => 'Kab. Aceh Tenggara'],
            ['provinsi_id' => 1, 'nama_kabupaten' => 'Kab. Aceh Timur'],
            ['provinsi_id' => 1, 'nama_kabupaten' => 'Kab. Aceh Utara'],
            ['provinsi_id' => 1, 'nama_kabupaten' => 'Kab. Bener Meriah'],
            ['provinsi_id' => 1, 'nama_kabupaten' => 'Kab. Bireuen'],
            ['provinsi_id' => 1, 'nama_kabupaten' => 'Kab. Gayo Lues'],
            ['provinsi_id' => 1, 'nama_kabupaten' => 'Kab. Nagan Raya'],
            ['provinsi_id' => 1, 'nama_kabupaten' => 'Kab. Pidie'],
            ['provinsi_id' => 1, 'nama_kabupaten' => 'Kab. Pidie Jaya'],
            ['provinsi_id' => 1, 'nama_kabupaten' => 'Kab. Simeulue'],
            ['provinsi_id' => 1, 'nama_kabupaten' => 'Kota Banda Aceh'],
            ['provinsi_id' => 1, 'nama_kabupaten' => 'Kota Langsa'],
            ['provinsi_id' => 1, 'nama_kabupaten' => 'Kota Lhokseumawe'],
            ['provinsi_id' => 1, 'nama_kabupaten' => 'Kota Sabang'],
            ['provinsi_id' => 1, 'nama_kabupaten' => 'Kota Subulussalam'],

            ['provinsi_id' => 2, 'nama_kabupaten' => 'Kab. Asahan'],
            ['provinsi_id' => 2, 'nama_kabupaten' => 'Kab. Batubara'],
            ['provinsi_id' => 2, 'nama_kabupaten' => 'Kab. Dairi'],
            ['provinsi_id' => 2, 'nama_kabupaten' => 'Kab. Deli Serdang'],
            ['provinsi_id' => 2, 'nama_kabupaten' => 'Kab. Humbang Hasundutan'],
            ['provinsi_id' => 2, 'nama_kabupaten' => 'Kab. Karo'],
            ['provinsi_id' => 2, 'nama_kabupaten' => 'Kab. Labuhanbatu'],
            ['provinsi_id' => 2, 'nama_kabupaten' => 'Kab. Labuhanbatu Selatan'],
            ['provinsi_id' => 2, 'nama_kabupaten' => 'Kab. Labuhanbatu Utara'],
            ['provinsi_id' => 2, 'nama_kabupaten' => 'Kab. Langkat'],
            ['provinsi_id' => 2, 'nama_kabupaten' => 'Kab. Mandailing Natal'],
            ['provinsi_id' => 2, 'nama_kabupaten' => 'Kab. Nias'],
            ['provinsi_id' => 2, 'nama_kabupaten' => 'Kab. Nias Barat'],
            ['provinsi_id' => 2, 'nama_kabupaten' => 'Kab. Nias Selatan'],
            ['provinsi_id' => 2, 'nama_kabupaten' => 'Kab. Nias Utara'],
            ['provinsi_id' => 2, 'nama_kabupaten' => 'Kab. Padang Lawas'],
            ['provinsi_id' => 2, 'nama_kabupaten' => 'Kab. Padang Lawas Utara'],
            ['provinsi_id' => 2, 'nama_kabupaten' => 'Kab. Pakpak Bharat'],
            ['provinsi_id' => 2, 'nama_kabupaten' => 'Kab. Samosir'],
            ['provinsi_id' => 2, 'nama_kabupaten' => 'Kab. Serdang Bedagai'],
            ['provinsi_id' => 2, 'nama_kabupaten' => 'Kab. Simalungun'],
            ['provinsi_id' => 2, 'nama_kabupaten' => 'Kab. Tapanuli Selatan'],
            ['provinsi_id' => 2, 'nama_kabupaten' => 'Kab. Tapanuli Tengah'],
            ['provinsi_id' => 2, 'nama_kabupaten' => 'Kab. Tapanuli Utara'],
            ['provinsi_id' => 2, 'nama_kabupaten' => 'Kab. Toba Samosir'],
            ['provinsi_id' => 2, 'nama_kabupaten' => 'Kota Binjai'],
            ['provinsi_id' => 2, 'nama_kabupaten' => 'Kota Gunungsitoli'],
            ['provinsi_id' => 2, 'nama_kabupaten' => 'Kota Medan'],
            ['provinsi_id' => 2, 'nama_kabupaten' => 'Kota Padangsidempuan'],
            ['provinsi_id' => 2, 'nama_kabupaten' => 'Kota Pematangsiantar'],
            ['provinsi_id' => 2, 'nama_kabupaten' => 'Kota Sibolga'],
            ['provinsi_id' => 2, 'nama_kabupaten' => 'Kota Tanjungbalai'],
            ['provinsi_id' => 2, 'nama_kabupaten' => 'Kota Tebing Tinggi'],
            
            ['provinsi_id' => 3, 'nama_kabupaten' => 'Kab. Banyuasin'],
            ['provinsi_id' => 3, 'nama_kabupaten' => 'Kab. Empat Lawang'],
            ['provinsi_id' => 3, 'nama_kabupaten' => 'Kab. Lahat'],
            ['provinsi_id' => 3, 'nama_kabupaten' => 'Kab. Muara Enim'],
            ['provinsi_id' => 3, 'nama_kabupaten' => 'Kab. Musi Banyuasin'],
            ['provinsi_id' => 3, 'nama_kabupaten' => 'Kab. Musi Rawas'],
            ['provinsi_id' => 3, 'nama_kabupaten' => 'Kab. Musi Rawas Utara'],
            ['provinsi_id' => 3, 'nama_kabupaten' => 'Kab. Ogan Ilir'],
            ['provinsi_id' => 3, 'nama_kabupaten' => 'Kab. Ogan Komering Ilir'],
            ['provinsi_id' => 3, 'nama_kabupaten' => 'Kab. Ogan Komering Ulu'],
            ['provinsi_id' => 3, 'nama_kabupaten' => 'Kab. Ogan Komering Ulu Selatan'],
            ['provinsi_id' => 3, 'nama_kabupaten' => 'Kab. Ogan Komering Ulu Timur'],
            ['provinsi_id' => 3, 'nama_kabupaten' => 'Kab. Penukal Abab Lematang Ilir'],
            ['provinsi_id' => 3, 'nama_kabupaten' => 'Kota Lubuklinggau'],
            ['provinsi_id' => 3, 'nama_kabupaten' => 'Kota Pagar Alam'],
            ['provinsi_id' => 3, 'nama_kabupaten' => 'Kota Palembang'],
            ['provinsi_id' => 3, 'nama_kabupaten' => 'Kota Prabumulih'],

            ['provinsi_id' => 4, 'nama_kabupaten' => 'Kab. Agam'],
            ['provinsi_id' => 4, 'nama_kabupaten' => 'Kab. Dharmasraya'],
            ['provinsi_id' => 4, 'nama_kabupaten' => 'Kab. Kepulauan Mentawai'],
            ['provinsi_id' => 4, 'nama_kabupaten' => 'Kab. Lima Puluh Kota'],
            ['provinsi_id' => 4, 'nama_kabupaten' => 'Kab. Padang Pariaman'],
            ['provinsi_id' => 4, 'nama_kabupaten' => 'Kab. Pasaman'],
            ['provinsi_id' => 4, 'nama_kabupaten' => 'Kab. Pasaman Barat'],
            ['provinsi_id' => 4, 'nama_kabupaten' => 'Kab. Pesisir Selatan'],
            ['provinsi_id' => 4, 'nama_kabupaten' => 'Kab. Sijunjung'],
            ['provinsi_id' => 4, 'nama_kabupaten' => 'Kab. Solok'],
            ['provinsi_id' => 4, 'nama_kabupaten' => 'Kab. Solok Selatan'],
            ['provinsi_id' => 4, 'nama_kabupaten' => 'Kab. Tanah Datar'],
            ['provinsi_id' => 4, 'nama_kabupaten' => 'Kota Bukittinggi'],
            ['provinsi_id' => 4, 'nama_kabupaten' => 'Kota Padang'],
            ['provinsi_id' => 4, 'nama_kabupaten' => 'Kota Padangpanjang'],
            ['provinsi_id' => 4, 'nama_kabupaten' => 'Kota Pariaman'],
            ['provinsi_id' => 4, 'nama_kabupaten' => 'Kota Payakumbuh'],
            ['provinsi_id' => 4, 'nama_kabupaten' => 'Kota Sawahlunto'],
            ['provinsi_id' => 4, 'nama_kabupaten' => 'Kota Solok'],

            //10
            ['provinsi_id' => 5, 'nama_kabupaten' => 'Kab. Bengkulu Selatan'],
            ['provinsi_id' => 5, 'nama_kabupaten' => 'Kab. Bengkulu Tengah'],
            ['provinsi_id' => 5, 'nama_kabupaten' => 'Kab. Bengkulu Utara'],
            ['provinsi_id' => 5, 'nama_kabupaten' => 'Kab. Kaur'],
            ['provinsi_id' => 5, 'nama_kabupaten' => 'Kab. Kepahiang'],
            ['provinsi_id' => 5, 'nama_kabupaten' => 'Kab. Lebong'],
            ['provinsi_id' => 5, 'nama_kabupaten' => 'Kab. Mukomuko'],
            ['provinsi_id' => 5, 'nama_kabupaten' => 'Kab. Rejang Lebong'],
            ['provinsi_id' => 5, 'nama_kabupaten' => 'Kab. Seluma'],
            ['provinsi_id' => 5, 'nama_kabupaten' => 'Kota Bengkulu'],

            //12
            ['provinsi_id' => 6, 'nama_kabupaten' => 'Kab. Bengkalis'],
            ['provinsi_id' => 6, 'nama_kabupaten' => 'Kab. Indragiri Hilir'],
            ['provinsi_id' => 6, 'nama_kabupaten' => 'Kab. Indragiri Hulu'],
            ['provinsi_id' => 6, 'nama_kabupaten' => 'Kab. Kampar'],
            ['provinsi_id' => 6, 'nama_kabupaten' => 'Kab. Kepulauan Meranti'],
            ['provinsi_id' => 6, 'nama_kabupaten' => 'Kab. Kuantan Singingi'],
            ['provinsi_id' => 6, 'nama_kabupaten' => 'Kab. Pelalawan'],
            ['provinsi_id' => 6, 'nama_kabupaten' => 'Kab. Rokan Hilir'],
            ['provinsi_id' => 6, 'nama_kabupaten' => 'Kab. Rokan Hulu'],
            ['provinsi_id' => 6, 'nama_kabupaten' => 'Kab. Siak'],
            ['provinsi_id' => 6, 'nama_kabupaten' => 'Kota Dumai'],
            ['provinsi_id' => 6, 'nama_kabupaten' => 'Kota Pekanbaru'],

            //7
            ['provinsi_id' => 7, 'nama_kabupaten' => 'Kab. Bintan'],
            ['provinsi_id' => 7, 'nama_kabupaten' => 'Kab. Karimun'],
            ['provinsi_id' => 7, 'nama_kabupaten' => 'Kab. Kepulauan Anambas'],
            ['provinsi_id' => 7, 'nama_kabupaten' => 'Kab. Lingga'],
            ['provinsi_id' => 7, 'nama_kabupaten' => 'Kab. Natuna'],
            ['provinsi_id' => 7, 'nama_kabupaten' => 'Kota Batam'],
            ['provinsi_id' => 7, 'nama_kabupaten' => 'Kota Tanjung Pinang'],

            ['provinsi_id' => 8, 'nama_kabupaten' => 'Kab. Batanghari'],
            ['provinsi_id' => 8, 'nama_kabupaten' => 'Kab. Bungo'],
            ['provinsi_id' => 8, 'nama_kabupaten' => 'Kab. Kerinci'],
            ['provinsi_id' => 8, 'nama_kabupaten' => 'Kab. Merangin'],
            ['provinsi_id' => 8, 'nama_kabupaten' => 'Kab. Muaro Jambi'],
            ['provinsi_id' => 8, 'nama_kabupaten' => 'Kab. Sarolangun'],
            ['provinsi_id' => 8, 'nama_kabupaten' => 'Kab. Tanjung Jabung Barat'],
            ['provinsi_id' => 8, 'nama_kabupaten' => 'Kab. Tanjung Jabung Timur'],
            ['provinsi_id' => 8, 'nama_kabupaten' => 'Kab. Tebo'],
            ['provinsi_id' => 8, 'nama_kabupaten' => 'Kota Jambi'],
            ['provinsi_id' => 8, 'nama_kabupaten' => 'Kota Sungai Penuh'],

            //15
            ['provinsi_id' => 9, 'nama_kabupaten' => 'Kab. Lampung Tengah'],
            ['provinsi_id' => 9, 'nama_kabupaten' => 'Kab. Lampung Utara'],
            ['provinsi_id' => 9, 'nama_kabupaten' => 'Kab. Lampung Selatan'],
            ['provinsi_id' => 9, 'nama_kabupaten' => 'Kab. Lampung Barat'],
            ['provinsi_id' => 9, 'nama_kabupaten' => 'Kab. Lampung Timur'],
            ['provinsi_id' => 9, 'nama_kabupaten' => 'Kab. Mesuji'],
            ['provinsi_id' => 9, 'nama_kabupaten' => 'Kab. Pesawaran'],
            ['provinsi_id' => 9, 'nama_kabupaten' => 'Kab. Pesisir Barat'],
            ['provinsi_id' => 9, 'nama_kabupaten' => 'Kab. Pringsewu'],
            ['provinsi_id' => 9, 'nama_kabupaten' => 'Kab. Tulang Bawang'],
            ['provinsi_id' => 9, 'nama_kabupaten' => 'Kab. Tulang Bawang Barat'],
            ['provinsi_id' => 9, 'nama_kabupaten' => 'Kab. Tanggamus'],
            ['provinsi_id' => 9, 'nama_kabupaten' => 'Kab. Way Kanan'],
            ['provinsi_id' => 9, 'nama_kabupaten' => 'Kota Bandar Lampung'],
            ['provinsi_id' => 9, 'nama_kabupaten' => 'Kota Metro'],

            ['provinsi_id' => 10, 'nama_kabupaten' => 'Kab. Bangka'],
            ['provinsi_id' => 10, 'nama_kabupaten' => 'Kab. Bangka Barat'],
            ['provinsi_id' => 10, 'nama_kabupaten' => 'Kab. Bangka Selatan'],
            ['provinsi_id' => 10, 'nama_kabupaten' => 'Kab. Bangka Tengah'],
            ['provinsi_id' => 10, 'nama_kabupaten' => 'Kab. Belitung'],
            ['provinsi_id' => 10, 'nama_kabupaten' => 'Kab. Belitung Timur'],
            ['provinsi_id' => 10, 'nama_kabupaten' => 'Kota Pangkal Pinang'],

            ['provinsi_id' => 11, 'nama_kabupaten' => 'Kab. Bengkayang'],
            ['provinsi_id' => 11, 'nama_kabupaten' => 'Kab. Kapuas Hulu'],
            ['provinsi_id' => 11, 'nama_kabupaten' => 'Kab. Kayong Utara'],
            ['provinsi_id' => 11, 'nama_kabupaten' => 'Kab. Ketapang'],
            ['provinsi_id' => 11, 'nama_kabupaten' => 'Kab. Kubu Raya'],
            ['provinsi_id' => 11, 'nama_kabupaten' => 'Kab. Landak'],
            ['provinsi_id' => 11, 'nama_kabupaten' => 'Kab. Melawi'],
            ['provinsi_id' => 11, 'nama_kabupaten' => 'Kab. Mempawah'],
            ['provinsi_id' => 11, 'nama_kabupaten' => 'Kab. Sambas'],
            ['provinsi_id' => 11, 'nama_kabupaten' => 'Kab. Sanggau'],
            ['provinsi_id' => 11, 'nama_kabupaten' => 'Kab. Sekadau'],
            ['provinsi_id' => 11, 'nama_kabupaten' => 'Kab. Sintang'],
            ['provinsi_id' => 11, 'nama_kabupaten' => 'Kota Pontianak'],
            ['provinsi_id' => 11, 'nama_kabupaten' => 'Kota Singkawang'],

            ['provinsi_id' => 12, 'nama_kabupaten' => 'Kab. Berau'],
            ['provinsi_id' => 12, 'nama_kabupaten' => 'Kab. Kutai Barat'],
            ['provinsi_id' => 12, 'nama_kabupaten' => 'Kab. Kutai Kartanegara'],
            ['provinsi_id' => 12, 'nama_kabupaten' => 'Kab. Kutai Timur'],
            ['provinsi_id' => 12, 'nama_kabupaten' => 'Kab. Mahakam Ulu'],
            ['provinsi_id' => 12, 'nama_kabupaten' => 'Kab. Paser'],
            ['provinsi_id' => 12, 'nama_kabupaten' => 'Kab. Penajam Paser Utara'],
            ['provinsi_id' => 12, 'nama_kabupaten' => 'Kota Balikpapan'],
            ['provinsi_id' => 12, 'nama_kabupaten' => 'Kota Bontang'],
            ['provinsi_id' => 12, 'nama_kabupaten' => 'Kota Samarinda'],

            ['provinsi_id' => 13, 'nama_kabupaten' => 'Kab. Balangan'],
            ['provinsi_id' => 13, 'nama_kabupaten' => 'Kab. Banjar'],
            ['provinsi_id' => 13, 'nama_kabupaten' => 'Kab. Barito Kuala'],
            ['provinsi_id' => 13, 'nama_kabupaten' => 'Kab. Hulu Sungai Selatan'],
            ['provinsi_id' => 13, 'nama_kabupaten' => 'Kab. Hulu Sungai Tengah'],
            ['provinsi_id' => 13, 'nama_kabupaten' => 'Kab. Hulu Sungai Utara'],
            ['provinsi_id' => 13, 'nama_kabupaten' => 'Kab. Kotabaru'],
            ['provinsi_id' => 13, 'nama_kabupaten' => 'Kab. Tabalong'],
            ['provinsi_id' => 13, 'nama_kabupaten' => 'Kab. Tanah Bumbu'],
            ['provinsi_id' => 13, 'nama_kabupaten' => 'Kab. Tanah Laut'],
            ['provinsi_id' => 13, 'nama_kabupaten' => 'Kab. Tapin'],
            ['provinsi_id' => 13, 'nama_kabupaten' => 'Kota Banjarbaru'],
            ['provinsi_id' => 13, 'nama_kabupaten' => 'Kota Banjarmasin'],

            ['provinsi_id' => 14, 'nama_kabupaten' => 'Kab. Barito Selatan'],
            ['provinsi_id' => 14, 'nama_kabupaten' => 'Kab. Barito Timur'],
            ['provinsi_id' => 14, 'nama_kabupaten' => 'Kab. Barito Utara'],
            ['provinsi_id' => 14, 'nama_kabupaten' => 'Kab. Gunung Mas'],
            ['provinsi_id' => 14, 'nama_kabupaten' => 'Kab. Kapuas'],
            ['provinsi_id' => 14, 'nama_kabupaten' => 'Kab. Katingan'],
            ['provinsi_id' => 14, 'nama_kabupaten' => 'Kab. Kotawaringin Barat'],
            ['provinsi_id' => 14, 'nama_kabupaten' => 'Kab. Kotawaringin Timur'],
            ['provinsi_id' => 14, 'nama_kabupaten' => 'Kab. Lamandau'],
            ['provinsi_id' => 14, 'nama_kabupaten' => 'Kab. Murung Raya'],
            ['provinsi_id' => 14, 'nama_kabupaten' => 'Kab. Pulang Pisau'],
            ['provinsi_id' => 14, 'nama_kabupaten' => 'Kab. Sukamara'],
            ['provinsi_id' => 14, 'nama_kabupaten' => 'Kab. Seruyan'],
            ['provinsi_id' => 14, 'nama_kabupaten' => 'Kota Palangka Raya'],

            ['provinsi_id' => 15, 'nama_kabupaten' => 'Kab. Bulungan'],
            ['provinsi_id' => 15, 'nama_kabupaten' => 'Kab. Malinau'],
            ['provinsi_id' => 15, 'nama_kabupaten' => 'Kab. Nunukan'],
            ['provinsi_id' => 15, 'nama_kabupaten' => 'Kab. Tana Tidung'],
            ['provinsi_id' => 15, 'nama_kabupaten' => 'Kota Tarakan'],

            ['provinsi_id' => 16, 'nama_kabupaten' => 'Kab. Lebak'],
            ['provinsi_id' => 16, 'nama_kabupaten' => 'Kab. Pandeglang'],
            ['provinsi_id' => 16, 'nama_kabupaten' => 'Kab. Serang'],
            ['provinsi_id' => 16, 'nama_kabupaten' => 'Kab. Tangerang'],
            ['provinsi_id' => 16, 'nama_kabupaten' => 'Kota Cilegon'],
            ['provinsi_id' => 16, 'nama_kabupaten' => 'Kota Serang'],
            ['provinsi_id' => 16, 'nama_kabupaten' => 'Kota Tangerang'],
            ['provinsi_id' => 16, 'nama_kabupaten' => 'Kota Tangerang Selatan'],

            ['provinsi_id' => 17, 'nama_kabupaten' => 'Kota Administrasi Jakarta Barat'],
            ['provinsi_id' => 17, 'nama_kabupaten' => 'Kota Administrasi Jakarta Pusat'],
            ['provinsi_id' => 17, 'nama_kabupaten' => 'Kota Administrasi Jakarta Selatan'],
            ['provinsi_id' => 17, 'nama_kabupaten' => 'Kota Administrasi Jakarta Timur'],
            ['provinsi_id' => 17, 'nama_kabupaten' => 'Kota Administrasi Jakarta Utara'],
            ['provinsi_id' => 17, 'nama_kabupaten' => 'Kab. Administrasi Kepulauan Seribu'],

            ['provinsi_id' => 18, 'nama_kabupaten' => 'Kab. Bandung'],
            ['provinsi_id' => 18, 'nama_kabupaten' => 'Kab. Bandung Barat'],
            ['provinsi_id' => 18, 'nama_kabupaten' => 'Kab. Bekasi'],
            ['provinsi_id' => 18, 'nama_kabupaten' => 'Kab. Bogor'],
            ['provinsi_id' => 18, 'nama_kabupaten' => 'Kab. Ciamis'],
            ['provinsi_id' => 18, 'nama_kabupaten' => 'Kab. Cianjur'],
            ['provinsi_id' => 18, 'nama_kabupaten' => 'Kab. Cirebon'],
            ['provinsi_id' => 18, 'nama_kabupaten' => 'Kab. Garut'],
            ['provinsi_id' => 18, 'nama_kabupaten' => 'Kab. Indramayu'],
            ['provinsi_id' => 18, 'nama_kabupaten' => 'Kab. Karawang'],
            ['provinsi_id' => 18, 'nama_kabupaten' => 'Kab. Kuningan'],
            ['provinsi_id' => 18, 'nama_kabupaten' => 'Kab. Majalengka'],
            ['provinsi_id' => 18, 'nama_kabupaten' => 'Kab. Pangandaran'],
            ['provinsi_id' => 18, 'nama_kabupaten' => 'Kab. Purwakarta'],
            ['provinsi_id' => 18, 'nama_kabupaten' => 'Kab. Subang'],
            ['provinsi_id' => 18, 'nama_kabupaten' => 'Kab. Sukabumi'],
            ['provinsi_id' => 18, 'nama_kabupaten' => 'Kab. Sumedang'],
            ['provinsi_id' => 18, 'nama_kabupaten' => 'Kab. Tasikmalaya'],
            ['provinsi_id' => 18, 'nama_kabupaten' => 'Kota Bandung'],
            ['provinsi_id' => 18, 'nama_kabupaten' => 'Kota Banjar'],
            ['provinsi_id' => 18, 'nama_kabupaten' => 'Kota Bekasi'],
            ['provinsi_id' => 18, 'nama_kabupaten' => 'Kota Bogor'],
            ['provinsi_id' => 18, 'nama_kabupaten' => 'Kota Cimahi'],
            ['provinsi_id' => 18, 'nama_kabupaten' => 'Kota Cirebon'],
            ['provinsi_id' => 18, 'nama_kabupaten' => 'Kota Depok'],
            ['provinsi_id' => 18, 'nama_kabupaten' => 'Kota Sukabumi'],
            ['provinsi_id' => 18, 'nama_kabupaten' => 'Kota Tasikmalaya'],

            ['provinsi_id' => 19, 'nama_kabupaten' => 'Kab. Banjarnegara'],
            ['provinsi_id' => 19, 'nama_kabupaten' => 'Kab. Banyumas'],
            ['provinsi_id' => 19, 'nama_kabupaten' => 'Kab. Batang'],
            ['provinsi_id' => 19, 'nama_kabupaten' => 'Kab. Blora'],
            ['provinsi_id' => 19, 'nama_kabupaten' => 'Kab. Boyolali'],
            ['provinsi_id' => 19, 'nama_kabupaten' => 'Kab. Brebes'],
            ['provinsi_id' => 19, 'nama_kabupaten' => 'Kab. Cilacap'],
            ['provinsi_id' => 19, 'nama_kabupaten' => 'Kab. Demak'],
            ['provinsi_id' => 19, 'nama_kabupaten' => 'Kab. Grobogan'],
            ['provinsi_id' => 19, 'nama_kabupaten' => 'Kab. Jepara'],
            ['provinsi_id' => 19, 'nama_kabupaten' => 'Kab. Karanganyar'],
            ['provinsi_id' => 19, 'nama_kabupaten' => 'Kab. Kebumen'],
            ['provinsi_id' => 19, 'nama_kabupaten' => 'Kab. Kendal'],
            ['provinsi_id' => 19, 'nama_kabupaten' => 'Kab. Klaten'],
            ['provinsi_id' => 19, 'nama_kabupaten' => 'Kab. Kudus'],
            ['provinsi_id' => 19, 'nama_kabupaten' => 'Kab. Magelang'],
            ['provinsi_id' => 19, 'nama_kabupaten' => 'Kab. Pati'],
            ['provinsi_id' => 19, 'nama_kabupaten' => 'Kab. Pekalongan'],
            ['provinsi_id' => 19, 'nama_kabupaten' => 'Kab. Pemalang'],
            ['provinsi_id' => 19, 'nama_kabupaten' => 'Kab. Purbalingga'],
            ['provinsi_id' => 19, 'nama_kabupaten' => 'Kab. Purworejo'],
            ['provinsi_id' => 19, 'nama_kabupaten' => 'Kab. Rembang'],
            ['provinsi_id' => 19, 'nama_kabupaten' => 'Kab. Semarang'],
            ['provinsi_id' => 19, 'nama_kabupaten' => 'Kab. Sragen'],
            ['provinsi_id' => 19, 'nama_kabupaten' => 'Kab. Sukoharjo'],
            ['provinsi_id' => 19, 'nama_kabupaten' => 'Kab. Tegal'],
            ['provinsi_id' => 19, 'nama_kabupaten' => 'Kab. Temanggung'],
            ['provinsi_id' => 19, 'nama_kabupaten' => 'Kab. Wonogiri'],
            ['provinsi_id' => 19, 'nama_kabupaten' => 'Kab. Wonosobo'],
            ['provinsi_id' => 19, 'nama_kabupaten' => 'Kota Magelang'],
            ['provinsi_id' => 19, 'nama_kabupaten' => 'Kota Pekalongan'],
            ['provinsi_id' => 19, 'nama_kabupaten' => 'Kota Salatiga'],
            ['provinsi_id' => 19, 'nama_kabupaten' => 'Kota Semarang'],
            ['provinsi_id' => 19, 'nama_kabupaten' => 'Kota Surakarta'],
            ['provinsi_id' => 19, 'nama_kabupaten' => 'Kota Tega'],

            ['provinsi_id' => 20, 'nama_kabupaten' => 'Kab. Bantul'],
            ['provinsi_id' => 20, 'nama_kabupaten' => 'Kab. Gunungkidul'],
            ['provinsi_id' => 20, 'nama_kabupaten' => 'Kab. Kulon Progo'],
            ['provinsi_id' => 20, 'nama_kabupaten' => 'Kab. Sleman'],
            ['provinsi_id' => 20, 'nama_kabupaten' => 'Kota Yogyakarta'],

            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kab. Bangkalan'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kab. Banyuwangi'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kab. Blitar'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kab. Bojonegoro'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kab. Bondowoso'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kab. Gresik'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kab. Jember'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kab. Jombang'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kab. Kediri'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kab. Lamongan'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kab. Lumajang'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kab. Madiun'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kab. Magetan'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kab. Malang'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kab. Mojokerto'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kab. Nganjuk'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kab. Ngawi'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kab. Pacitan'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kab. Pamekasan'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kab. Pasuruan'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kab. Ponorogo'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kab. Probolinggo'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kab. Sampang'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kab. Sidoarjo'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kab. Situbondo'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kab. Sumenep'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kab. Trenggalek'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kab. Tuban'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kab. Tulungagung'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kota Batu'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kota Blitar'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kota Kediri'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kota Madiun'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kota Malang'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kota Mojokerto'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kota Pasuruan'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kota Probolinggo'],
            ['provinsi_id' => 21, 'nama_kabupaten' => 'Kota Surabaya'],

            ['provinsi_id' => 22, 'nama_kabupaten' => 'Kab. Badung'],
            ['provinsi_id' => 22, 'nama_kabupaten' => 'Kab. Bangli'],
            ['provinsi_id' => 22, 'nama_kabupaten' => 'Kab. Buleleng'],
            ['provinsi_id' => 22, 'nama_kabupaten' => 'Kab. Gianyar'],
            ['provinsi_id' => 22, 'nama_kabupaten' => 'Kab. Jembrana'],
            ['provinsi_id' => 22, 'nama_kabupaten' => 'Kab. Karangasem'],
            ['provinsi_id' => 22, 'nama_kabupaten' => 'Kab. Klungkung'],
            ['provinsi_id' => 22, 'nama_kabupaten' => 'Kab. Tabanan'],
            ['provinsi_id' => 22, 'nama_kabupaten' => 'Kota Denpasar'],

            ['provinsi_id' => 23, 'nama_kabupaten' => 'Kab. Alor'],
            ['provinsi_id' => 23, 'nama_kabupaten' => 'Kab. Belu'],
            ['provinsi_id' => 23, 'nama_kabupaten' => 'Kab. Ende'],
            ['provinsi_id' => 23, 'nama_kabupaten' => 'Kab. Flores Timur'],
            ['provinsi_id' => 23, 'nama_kabupaten' => 'Kab. Kupang'],
            ['provinsi_id' => 23, 'nama_kabupaten' => 'Kab. Lembata'],
            ['provinsi_id' => 23, 'nama_kabupaten' => 'Kab. Malaka'],
            ['provinsi_id' => 23, 'nama_kabupaten' => 'Kab. Manggarai'],
            ['provinsi_id' => 23, 'nama_kabupaten' => 'Kab. Manggarai Barat'],
            ['provinsi_id' => 23, 'nama_kabupaten' => 'Kab. Manggarai Timur'],
            ['provinsi_id' => 23, 'nama_kabupaten' => 'Kab. Ngada'],
            ['provinsi_id' => 23, 'nama_kabupaten' => 'Kab. Nagekeo'],
            ['provinsi_id' => 23, 'nama_kabupaten' => 'Kab. Rote Ndao'],
            ['provinsi_id' => 23, 'nama_kabupaten' => 'Kab. Sabu Raijua'],
            ['provinsi_id' => 23, 'nama_kabupaten' => 'Kab. Sikka'],
            ['provinsi_id' => 23, 'nama_kabupaten' => 'Kab. Sumba Barat'],
            ['provinsi_id' => 23, 'nama_kabupaten' => 'Kab. Sumba Barat Daya'],
            ['provinsi_id' => 23, 'nama_kabupaten' => 'Kab. Sumba Tengah'],
            ['provinsi_id' => 23, 'nama_kabupaten' => 'Kab. Sumba Timur'],
            ['provinsi_id' => 23, 'nama_kabupaten' => 'Kab. Timor Tengah Selatan'],
            ['provinsi_id' => 23, 'nama_kabupaten' => 'Kab. Timor Tengah Utara'],
            ['provinsi_id' => 23, 'nama_kabupaten' => 'Kota Kupang'],

            ['provinsi_id' => 24, 'nama_kabupaten' => 'Kab. Bima'],
            ['provinsi_id' => 24, 'nama_kabupaten' => 'Kab. Dompu'],
            ['provinsi_id' => 24, 'nama_kabupaten' => 'Kab. Lombok Barat'],
            ['provinsi_id' => 24, 'nama_kabupaten' => 'Kab. Lombok Tengah'],
            ['provinsi_id' => 24, 'nama_kabupaten' => 'Kab. Lombok Timur'],
            ['provinsi_id' => 24, 'nama_kabupaten' => 'Kab. Lombok Utara'],
            ['provinsi_id' => 24, 'nama_kabupaten' => 'Kab. Sumbawa'],
            ['provinsi_id' => 24, 'nama_kabupaten' => 'Kab. Sumbawa Barat'],
            ['provinsi_id' => 24, 'nama_kabupaten' => 'Kota Bima'],
            ['provinsi_id' => 24, 'nama_kabupaten' => 'Kota Mataram'],
            
            ['provinsi_id' => 25, 'nama_kabupaten' => 'Kab. Boalemo'],
            ['provinsi_id' => 25, 'nama_kabupaten' => 'Kab. Bone Bolango'],
            ['provinsi_id' => 25, 'nama_kabupaten' => 'Kab. Gorontalo'],
            ['provinsi_id' => 25, 'nama_kabupaten' => 'Kab. Gorontalo Utara'],
            ['provinsi_id' => 25, 'nama_kabupaten' => 'Kab. Pohuwato'],
            ['provinsi_id' => 25, 'nama_kabupaten' => 'Kota Gorontalo'],

            ['provinsi_id' => 26, 'nama_kabupaten' => 'Kab. Majene'],
            ['provinsi_id' => 26, 'nama_kabupaten' => 'Kab. Mamasa'],
            ['provinsi_id' => 26, 'nama_kabupaten' => 'Kab. Mamuju'],
            ['provinsi_id' => 26, 'nama_kabupaten' => 'Kab. Mamuju Tengah'],
            ['provinsi_id' => 26, 'nama_kabupaten' => 'Kab. Mamuju Utara'],
            ['provinsi_id' => 26, 'nama_kabupaten' => 'Kab. Polewali Mandar'],
            ['provinsi_id' => 26, 'nama_kabupaten' => 'Kota Mamuju'],

            ['provinsi_id' => 27, 'nama_kabupaten' => 'Kab. Banggai'],
            ['provinsi_id' => 27, 'nama_kabupaten' => 'Kab. Banggai Kepulauan'],
            ['provinsi_id' => 27, 'nama_kabupaten' => 'Kab. Banggai Laut'],
            ['provinsi_id' => 27, 'nama_kabupaten' => 'Kab. Buol'],
            ['provinsi_id' => 27, 'nama_kabupaten' => 'Kab. Donggala'],
            ['provinsi_id' => 27, 'nama_kabupaten' => 'Kab. Morowali'],
            ['provinsi_id' => 27, 'nama_kabupaten' => 'Kab. Morowali Utara'],
            ['provinsi_id' => 27, 'nama_kabupaten' => 'Kab. Parigi Moutong'],
            ['provinsi_id' => 27, 'nama_kabupaten' => 'Kab. Poso'],
            ['provinsi_id' => 27, 'nama_kabupaten' => 'Kab. Sigi'],
            ['provinsi_id' => 27, 'nama_kabupaten' => 'Kab. Tojo Una-Una'],
            ['provinsi_id' => 27, 'nama_kabupaten' => 'Kab. Toli-Toli'],
            ['provinsi_id' => 27, 'nama_kabupaten' => 'Kota Palu'],

            ['provinsi_id' => 28, 'nama_kabupaten' => 'Kab. Bolaang Mongondow'],
            ['provinsi_id' => 28, 'nama_kabupaten' => 'Kab. Bolaang Mongondow Selatan'],
            ['provinsi_id' => 28, 'nama_kabupaten' => 'Kab. Bolaang Mongondow Timur'],
            ['provinsi_id' => 28, 'nama_kabupaten' => 'Kab. Bolaang Mongondow Utara'],
            ['provinsi_id' => 28, 'nama_kabupaten' => 'Kab. Kepulauan Sangihe'],
            ['provinsi_id' => 28, 'nama_kabupaten' => 'Kab. Kepulauan Siau Tagulandang Biaro'],
            ['provinsi_id' => 28, 'nama_kabupaten' => 'Kab. Kepulauan Talaud'],
            ['provinsi_id' => 28, 'nama_kabupaten' => 'Kab. Minahasa'],
            ['provinsi_id' => 28, 'nama_kabupaten' => 'Kab. Minahasa Selatan'],
            ['provinsi_id' => 28, 'nama_kabupaten' => 'Kab. Minahasa Tenggara'],
            ['provinsi_id' => 28, 'nama_kabupaten' => 'Kab. Minahasa Utara'],
            ['provinsi_id' => 28, 'nama_kabupaten' => 'Kota Bitung'],
            ['provinsi_id' => 28, 'nama_kabupaten' => 'Kota Kotamobagu'],
            ['provinsi_id' => 28, 'nama_kabupaten' => 'Kota Manado'],
            ['provinsi_id' => 28, 'nama_kabupaten' => 'Kota Tomohon'],

            ['provinsi_id' => 29, 'nama_kabupaten' => 'Kab. Bombana'],
            ['provinsi_id' => 29, 'nama_kabupaten' => 'Kab. Buton'],
            ['provinsi_id' => 29, 'nama_kabupaten' => 'Kab. Buton Selatan'],
            ['provinsi_id' => 29, 'nama_kabupaten' => 'Kab. Buton Tengah'],
            ['provinsi_id' => 29, 'nama_kabupaten' => 'Kab. Buton Utara'],
            ['provinsi_id' => 29, 'nama_kabupaten' => 'Kab. Kolaka'],
            ['provinsi_id' => 29, 'nama_kabupaten' => 'Kab. Kolaka Timur'],
            ['provinsi_id' => 29, 'nama_kabupaten' => 'Kab. Kolaka Utara'],
            ['provinsi_id' => 29, 'nama_kabupaten' => 'Kab. Konawe'],
            ['provinsi_id' => 29, 'nama_kabupaten' => 'Kab. Konawe Kepulauan'],
            ['provinsi_id' => 29, 'nama_kabupaten' => 'Kab. Konawe Selatan'],
            ['provinsi_id' => 29, 'nama_kabupaten' => 'Kab. Konawe Utara'],
            ['provinsi_id' => 29, 'nama_kabupaten' => 'Kab. Muna'],
            ['provinsi_id' => 29, 'nama_kabupaten' => 'Kab. Muna Barat'],
            ['provinsi_id' => 29, 'nama_kabupaten' => 'Kab. Wakatobi'],
            ['provinsi_id' => 29, 'nama_kabupaten' => 'Kota Bau-Bau'],
            ['provinsi_id' => 29, 'nama_kabupaten' => 'Kota Kendari'],

            ['provinsi_id' => 30, 'nama_kabupaten' => 'Kab. Bantaeng'],
            ['provinsi_id' => 30, 'nama_kabupaten' => 'Kab. Barru'],
            ['provinsi_id' => 30, 'nama_kabupaten' => 'Kab. Bone'],
            ['provinsi_id' => 30, 'nama_kabupaten' => 'Kab. Bulukumba'],
            ['provinsi_id' => 30, 'nama_kabupaten' => 'Kab. Enrekang'],
            ['provinsi_id' => 30, 'nama_kabupaten' => 'Kab. Gowa'],
            ['provinsi_id' => 30, 'nama_kabupaten' => 'Kab. Jeneponto'],
            ['provinsi_id' => 30, 'nama_kabupaten' => 'Kab. Kepulauan Selayar'],
            ['provinsi_id' => 30, 'nama_kabupaten' => 'Kab. Luwu'],
            ['provinsi_id' => 30, 'nama_kabupaten' => 'Kab. Luwu Timur'],
            ['provinsi_id' => 30, 'nama_kabupaten' => 'Kab. Luwu Utara'],
            ['provinsi_id' => 30, 'nama_kabupaten' => 'Kab. Maros'],
            ['provinsi_id' => 30, 'nama_kabupaten' => 'Kab. Pangkajene dan Kepulauan'],
            ['provinsi_id' => 30, 'nama_kabupaten' => 'Kab. Pinrang'],
            ['provinsi_id' => 30, 'nama_kabupaten' => 'Kab. Sidenreng Rappang'],
            ['provinsi_id' => 30, 'nama_kabupaten' => 'Kab. Sinjai'],
            ['provinsi_id' => 30, 'nama_kabupaten' => 'Kab. Soppeng'],
            ['provinsi_id' => 30, 'nama_kabupaten' => 'Kab. Takalar'],
            ['provinsi_id' => 30, 'nama_kabupaten' => 'Kab. Tana Toraja'],
            ['provinsi_id' => 30, 'nama_kabupaten' => 'Kab. Toraja Utara'],
            ['provinsi_id' => 30, 'nama_kabupaten' => 'Kab. Wajo'],
            ['provinsi_id' => 30, 'nama_kabupaten' => 'Kota Makassar'],
            ['provinsi_id' => 30, 'nama_kabupaten' => 'Kota Palopo'],
            ['provinsi_id' => 30, 'nama_kabupaten' => 'Kota Parepare'],

            ['provinsi_id' => 31, 'nama_kabupaten' => 'Kab. Halmahera Barat'],
            ['provinsi_id' => 31, 'nama_kabupaten' => 'Kab. Halmahera Tengah'],
            ['provinsi_id' => 31, 'nama_kabupaten' => 'Kab. Halmahera Utara'],
            ['provinsi_id' => 31, 'nama_kabupaten' => 'Kab. Halmahera Selatan'],
            ['provinsi_id' => 31, 'nama_kabupaten' => 'Kab. Kepulauan Sula'],
            ['provinsi_id' => 31, 'nama_kabupaten' => 'Kab. Halmahera Timur'],
            ['provinsi_id' => 31, 'nama_kabupaten' => 'Kab. Pulau Morotai'],
            ['provinsi_id' => 31, 'nama_kabupaten' => 'Kab. Pulau Taliabu'],
            ['provinsi_id' => 31, 'nama_kabupaten' => 'Kota Ternate'],
            ['provinsi_id' => 31, 'nama_kabupaten' => 'Kota Tidore Kepulauan'],

            ['provinsi_id' => 32, 'nama_kabupaten' => 'Kab. Buru'],
            ['provinsi_id' => 32, 'nama_kabupaten' => 'Kab. Buru Selatan'],
            ['provinsi_id' => 32, 'nama_kabupaten' => 'Kab. Kepulauan Aru'],
            ['provinsi_id' => 32, 'nama_kabupaten' => 'Kab. Maluku Barat Daya'],
            ['provinsi_id' => 32, 'nama_kabupaten' => 'Kab. Maluku Tengah'],
            ['provinsi_id' => 32, 'nama_kabupaten' => 'Kab. Maluku Tenggara'],
            ['provinsi_id' => 32, 'nama_kabupaten' => 'Kab. Maluku Tenggara Barat'],
            ['provinsi_id' => 32, 'nama_kabupaten' => 'Kab. Seram Bagian Barat'],
            ['provinsi_id' => 32, 'nama_kabupaten' => 'Kab. Seram Bagian Timur'],
            ['provinsi_id' => 32, 'nama_kabupaten' => 'Kota Ambon'],
            ['provinsi_id' => 32, 'nama_kabupaten' => 'Kota Tual'],

            ['provinsi_id' => 33, 'nama_kabupaten' => 'Kab. Fakfak'],
            ['provinsi_id' => 33, 'nama_kabupaten' => 'Kab. Kaimana'],
            ['provinsi_id' => 33, 'nama_kabupaten' => 'Kab. Manokwari'],
            ['provinsi_id' => 33, 'nama_kabupaten' => 'Kab. Manokwari Selatan'],
            ['provinsi_id' => 33, 'nama_kabupaten' => 'Kab. Maybrat'],
            ['provinsi_id' => 33, 'nama_kabupaten' => 'Kab. Pegunungan Arfak'],
            ['provinsi_id' => 33, 'nama_kabupaten' => 'Kab. Raja Ampat'],
            ['provinsi_id' => 33, 'nama_kabupaten' => 'Kab. Sorong'],
            ['provinsi_id' => 33, 'nama_kabupaten' => 'Kab. Sorong Selatan'],
            ['provinsi_id' => 33, 'nama_kabupaten' => 'Kab. Tambrauw'],
            ['provinsi_id' => 33, 'nama_kabupaten' => 'Kab. Teluk Bintuni'],
            ['provinsi_id' => 33, 'nama_kabupaten' => 'Kab. Teluk Wondama'],

            ['provinsi_id' => 34, 'nama_kabupaten' => 'Kab. Asmat'],
            ['provinsi_id' => 34, 'nama_kabupaten' => 'Kab. Biak Numfor'],
            ['provinsi_id' => 34, 'nama_kabupaten' => 'Kab. Boven Digoel'],
            ['provinsi_id' => 34, 'nama_kabupaten' => 'Kab. Deiyai'],
            ['provinsi_id' => 34, 'nama_kabupaten' => 'Kab. Dogiyai'],
            ['provinsi_id' => 34, 'nama_kabupaten' => 'Kab. Intan Jaya'],
            ['provinsi_id' => 34, 'nama_kabupaten' => 'Kab. Jayapura'],
            ['provinsi_id' => 34, 'nama_kabupaten' => 'Kab. Jayawijaya'],
            ['provinsi_id' => 34, 'nama_kabupaten' => 'Kab. Keerom'],
            ['provinsi_id' => 34, 'nama_kabupaten' => 'Kab. Kepulauan Yapen'],
            ['provinsi_id' => 34, 'nama_kabupaten' => 'Kab. Lanny Jaya'],
            ['provinsi_id' => 34, 'nama_kabupaten' => 'Kab. Mamberamo Raya'],
            ['provinsi_id' => 34, 'nama_kabupaten' => 'Kab. Mamberamo Tengah'],
            ['provinsi_id' => 34, 'nama_kabupaten' => 'Kab. Mappi'],
            ['provinsi_id' => 34, 'nama_kabupaten' => 'Kab. Merauke'],
            ['provinsi_id' => 34, 'nama_kabupaten' => 'Kab. Mimika'],
            ['provinsi_id' => 34, 'nama_kabupaten' => 'Kab. Nabire'],
            ['provinsi_id' => 34, 'nama_kabupaten' => 'Kab. Nduga'],
            ['provinsi_id' => 34, 'nama_kabupaten' => 'Kab. Paniai'],
            ['provinsi_id' => 34, 'nama_kabupaten' => 'Kab. Pegunungan Bintang'],
            ['provinsi_id' => 34, 'nama_kabupaten' => 'Kab. Puncak'],
            ['provinsi_id' => 34, 'nama_kabupaten' => 'Kab. Puncak Jaya'],
            ['provinsi_id' => 34, 'nama_kabupaten' => 'Kab. Sarmi'],
            ['provinsi_id' => 34, 'nama_kabupaten' => 'Kab. Supiori'],
            ['provinsi_id' => 34, 'nama_kabupaten' => 'Kab. Tolikara'],
            ['provinsi_id' => 34, 'nama_kabupaten' => 'Kab. Waropen'],
            ['provinsi_id' => 34, 'nama_kabupaten' => 'Kab. Yahukimo'],
            ['provinsi_id' => 34, 'nama_kabupaten' => 'Kab. Yalimo'],
            ['provinsi_id' => 34, 'nama_kabupaten' => 'Kota Jayapura'],
        ];

        // Masukkan data ke dalam tabel
        DB::table('kabupatens')->insert($kabupatens);
    }
}
